package com.wabao.service.dao;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.wabao.service.bean.Book;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface BookDao {

	public Book findBookById(Integer id);
	
	public Integer insert(Book param);
	
	public Integer getBookCount(Book param);
	
	public List<Book> findBooksByPage(@Param("param")Book param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteBookById(Integer id);
}