package com.wabao.service.dao;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.wabao.service.bean.Havebook;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface HavebookDao {

	public Havebook findHavebookById(Integer id);
	
	public Integer insert(Havebook param);
	
	public Integer getHavebookCount(Havebook param);
	
	public List<Havebook> findHavebooksByPage(@Param("param")Havebook param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteHavebookById(Integer id);
}