package com.wabao.service.dao;

import java.util.List;
import java.lang.Integer;
import org.apache.ibatis.annotations.Param;
import com.wabao.service.bean.Userdb;

/**
 *
 * This tools just a simple useful tools, gen table to javabean
 *
 * "I hope this tools can save your time"
 *
 * Generated by <tt>Generate</tt> 
 *
 * @author com.ypn.mapi.generate
 * @version v1.0
 */
public interface UserdbDao {

	public Userdb findUserdbById(Integer id);
	
	public Integer insert(Userdb param);
	
	public Integer getUserdbCount(Userdb param);
	
	public List<Userdb> findUserdbsByPage(@Param("param")Userdb param,@Param("offset")Integer offset,@Param("rows")Integer rows);
	
	//if not use,pls delete it
	public Integer deleteUserdbById(Integer id);
}